# Generated by Django 5.1.2 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_school_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTwoFactorAuth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("encrypted_secret", models.TextField(blank=True, verbose_name="سر المصادقة المشفر")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="مفعلة")),
                ("recovery_code_hashes", models.JSONField(blank=True, default=list, verbose_name="رموز الاسترداد المشفرة")),
                ("last_used_counter", models.BigIntegerField(blank=True, null=True, verbose_name="آخر عداد مستخدم")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True, verbose_name="تاريخ التفعيل")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصادقة ثنائية",
                "verbose_name_plural": "المصادقة الثنائية",
            },
        ),
    ]
