# Generated by Django 5.2.16 on 2026-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_refine_school_year_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="البريد الموثّق يضمن وصول الفواتير وروابط استعادة كلمة المرور.",
                null=True,
                verbose_name="تاريخ توثيق البريد",
            ),
        ),
    ]
