# Generated by Django 5.2.16 on 2026-08-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_userprofile_email_verified_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolSubscription",
        ),
    ]
