# Generated by Django 5.2.16 on 2026-08-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_delete_schoolsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_schools",
        ),
    ]
