# Generated by Django 5.2.16 on 2026-08-04 20:00

from django.db import migrations, models


def retire_weather_occasion(apps, schema_editor):
    """شاشة مثبّتة على ثيم «حالة جوية» تعود إلى الوضع التلقائي.

    الثيم لم يعد موجودًا، وتركه سيجعل الشاشة تطلب ثيمًا لا يعرفه العرض فتبقى
    بلا مناسبة إلى الأبد دون أن يفهم المدير السبب.
    """
    DisplayScreen = apps.get_model("core", "DisplayScreen")
    DisplayScreen.objects.filter(occasion_theme="weather").update(occasion_theme="auto")


def restore_weather_occasion(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_remove_subscriptionplan_max_schools"),
    ]

    operations = [
        migrations.RunPython(retire_weather_occasion, restore_weather_occasion),
        migrations.AlterField(
            model_name="displayscreen",
            name="occasion_theme",
            field=models.CharField(
                choices=[
                    ("auto", "تلقائي حسب التنبيه"),
                    ("off", "بدون قالب مناسبة"),
                    ("national_day", "اليوم الوطني السعودي"),
                    ("founding_day", "يوم التأسيس"),
                    ("flag_day", "يوم العلم السعودي"),
                    ("ramadan", "شهر رمضان المبارك"),
                    ("eid_fitr", "عيد الفطر"),
                    ("eid_adha", "عيد الأضحى"),
                    ("teachers_day", "يوم المعلم"),
                    ("back_to_school", "العودة للدراسة"),
                    ("graduation", "حفل التخرج"),
                ],
                default="auto",
                help_text="يمكن تفعيله تلقائيًا من التنبيهات أو تثبيت قالب لهذه الشاشة فقط.",
                max_length=30,
                verbose_name="قالب المناسبة",
            ),
        ),
    ]
