OCCASION_TEMPLATES = {
    "national_day": {
        "name": "اليوم الوطني السعودي",
        "icon": "🇸🇦",
        "title": "دام عزك يا وطن",
        "body": "نحتفي اليوم بوطننا الغالي، ونسأل الله أن يديم على المملكة أمنها وعزها وازدهارها.",
        "level": "success",
        "theme": "national_day",
        "theme_name": "أخضر الوطن",
        "primary": "#006c35",
        "secondary": "#d4af37",
        "duration_hours": 24,
    },
    "founding_day": {
        "name": "يوم التأسيس",
        "icon": "🏛️",
        "title": "يوم بدينا",
        "body": "نحتفي بذكرى تأسيس الدولة السعودية، وبجذور راسخة تمتد لأكثر من ثلاثة قرون.",
        "level": "success",
        "theme": "founding_day",
        "theme_name": "الهوية النجدية",
        "primary": "#7a4b2a",
        "secondary": "#d9b382",
        "duration_hours": 24,
    },
    "teachers_day": {
        "name": "يوم المعلم",
        "icon": "👩‍🏫",
        "title": "شكرًا معلمينا",
        "body": "بكم تُبنى الأجيال وتزدهر المعرفة. شكرًا لعطائكم المتواصل.",
        "level": "success",
        "theme": "teachers_day",
        "theme_name": "المعرفة والعطاء",
        "primary": "#12355b",
        "secondary": "#f2c14e",
        "duration_hours": 24,
    },
    "back_to_school": {
        "name": "العودة للدراسة",
        "icon": "🎒",
        "title": "أهلًا بعودتكم",
        "body": "عام دراسي جديد مليء بالإنجاز والتعلم. نتمنى للجميع بداية موفقة.",
        "level": "info",
        "theme": "back_to_school",
        "theme_name": "بداية مشرقة",
        "primary": "#1261a0",
        "secondary": "#ffd166",
        "duration_hours": 24,
    },
    "graduation": {
        "name": "حفل التخرج",
        "icon": "🎓",
        "title": "مبارك التخرج",
        "body": "نبارك لطلابنا وطالباتنا تخرجهم، ونتمنى لهم مستقبلًا حافلًا بالنجاح.",
        "level": "success",
        "theme": "graduation",
        "theme_name": "ليلة الإنجاز",
        "primary": "#54278f",
        "secondary": "#f4c95d",
        "duration_hours": 12,
    },
    "weather": {
        "name": "تنبيه حالة جوية",
        "icon": "🌧️",
        "title": "تنبيه جوي",
        "body": "نرجو اتباع تعليمات السلامة ومتابعة القنوات الرسمية.",
        "level": "warning",
        "theme": "weather",
        "theme_name": "الطقس والسلامة",
        "primary": "#075985",
        "secondary": "#67e8f9",
        "duration_hours": 6,
    },
}
