# Generated by Django 6.0.7 on 2026-07-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0008_emergencyalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="occasion_theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "بدون ثيم مناسبة"),
                    ("national_day", "اليوم الوطني السعودي"),
                    ("founding_day", "يوم التأسيس"),
                    ("teachers_day", "يوم المعلم"),
                    ("back_to_school", "العودة للدراسة"),
                    ("graduation", "حفل التخرج"),
                    ("weather", "حالة جوية"),
                ],
                default="",
                help_text="يغيّر مظهر شاشة العرض طوال فترة نشاط هذا الإعلان.",
                max_length=30,
                verbose_name="ثيم المناسبة",
            ),
        ),
    ]
