# Generated by Django 5.2.16 on 2026-08-04 20:00

from django.db import migrations, models


def retire_weather_occasion(apps, schema_editor):
    """«حالة جوية» لم تعد مناسبة — انتقلت إلى تنبيهات الطوارئ.

    التنبيهات التي كانت تحملها تفقد ثيمها فقط؛ نصّها ونافذتها الزمنية تبقى
    كما هي. حذف الثيم أصدق من إبقاء مفتاح لا يعرفه العرض.
    """
    Announcement = apps.get_model("notices", "Announcement")
    Announcement.objects.filter(occasion_theme="weather").update(occasion_theme="")


def restore_weather_occasion(apps, schema_editor):
    # لا يمكن استرجاع ما فُقد؛ التراجع يعيد بنية الحقل فقط.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0010_announcement_screens"),
    ]

    operations = [
        migrations.RunPython(retire_weather_occasion, restore_weather_occasion),
        migrations.AlterField(
            model_name="announcement",
            name="occasion_theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "بدون ثيم مناسبة"),
                    ("national_day", "اليوم الوطني السعودي"),
                    ("founding_day", "يوم التأسيس"),
                    ("flag_day", "يوم العلم السعودي"),
                    ("ramadan", "شهر رمضان المبارك"),
                    ("eid_fitr", "عيد الفطر"),
                    ("eid_adha", "عيد الأضحى"),
                    ("teachers_day", "يوم المعلم"),
                    ("back_to_school", "العودة للدراسة"),
                    ("graduation", "حفل التخرج"),
                ],
                default="",
                help_text="يغيّر مظهر شاشة العرض طوال فترة نشاط هذا الإعلان.",
                max_length=30,
                verbose_name="ثيم المناسبة",
            ),
        ),
    ]
