# Generated by Django 5.2.16 on 2026-08-09 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0021_screen_offline_alert_window"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="مثال: إجازة عيد الفطر، إجازة منتصف الفصل، يوم التأسيس.",
                        max_length=120,
                        verbose_name="المناسبة",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="من تاريخ")),
                (
                    "end_date",
                    models.DateField(
                        help_text="يوم واحد؟ اجعل التاريخين متطابقين.",
                        verbose_name="إلى تاريخ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="schedule.schoolsettings",
                        verbose_name="إعدادات المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجازة مدرسية",
                "verbose_name_plural": "الإجازات المدرسية",
                "ordering": ("-start_date", "-id"),
                "indexes": [
                    models.Index(
                        fields=["settings", "start_date", "end_date"],
                        name="ix_closure_range",
                    )
                ],
            },
        ),
    ]
