# Generated by Django 5.2.16 on 2026-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0023_remove_screen_offline_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="bell_sound",
            field=models.CharField(
                choices=[
                    ("bell", "جرس المدرسة الافتراضي"),
                    ("elevator_announcement_bells", "أجراس إعلان المصعد"),
                ],
                default="bell",
                help_text="الصوت الذي يعمل عند بداية الحصة ونهاية الحصة السابقة.",
                max_length=40,
                verbose_name="صوت الجرس",
            ),
        ),
    ]
