# Generated by Django 5.2.16 on 2026-07-23 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="نوع الحدث"
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="مفتاح منع التكرار"
                    ),
                ),
                ("message", models.TextField(verbose_name="نص التنبيه")),
                (
                    "action_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="رابط الإجراء"
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="نص زر الإجراء"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار الإرسال"),
                            ("processing", "قيد الإرسال"),
                            ("sent", "تم الإرسال"),
                            ("failed", "فشل نهائيًا"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="عدد المحاولات"
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="موعد المحاولة التالية",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت حجز الرسالة"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "telegram_message_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="معرّف رسالة تيليجرام"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="آخر خطأ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "تنبيه تيليجرام",
                "verbose_name_plural": "تنبيهات تيليجرام",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"],
                        name="tg_alert_status_due_idx",
                    )
                ],
            },
        ),
    ]
