# Generated by Django 6.0.7 on 2026-08-02 14:30

import django.db.models.deletion
import django.utils.timezone
import subscriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_displayscreen_customization"),
        ("subscriptions", "0014_subscriptionrequest_receipt_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptioninvoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "تحويل"),
                    ("payment_link", "رابط دفع"),
                    ("tamara", "تمارا"),
                    ("moyasar", "ميسر"),
                ],
                max_length=20,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentoperation",
            name="method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "تحويل"),
                    ("payment_link", "رابط دفع"),
                    ("tamara", "تمارا"),
                    ("moyasar", "ميسر"),
                ],
                max_length=20,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.CreateModel(
            name="MoyasarCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_reference",
                    models.CharField(
                        default=subscriptions.models._moyasar_reference,
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="مرجع التاجر",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="رقم دفعة ميسر",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("renewal", "طلب تجديد"), ("new", "طلب اشتراك جديد")],
                        max_length=20,
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="بداية الاشتراك المطلوبة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "بانتظار الدفع"),
                            ("paid", "مدفوعة"),
                            ("authorized", "مصرح بها"),
                            ("captured", "مكتملة"),
                            ("failed", "فشلت"),
                            ("refunded", "مستردة"),
                            ("voided", "ملغاة"),
                            ("error", "خطأ"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "live_mode",
                    models.BooleanField(default=False, verbose_name="عملية فعلية"),
                ),
                (
                    "last_event",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="آخر حدث"
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="رسالة الخطأ",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moyasar_checkouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئت بواسطة",
                    ),
                ),
                (
                    "payment_operation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moyasar_checkout",
                        to="subscriptions.subscriptionpaymentoperation",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moyasar_checkouts",
                        to="core.subscriptionplan",
                        verbose_name="الخطة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moyasar_checkouts",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moyasar_checkouts",
                        to="subscriptions.schoolsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة دفع ميسر",
                "verbose_name_plural": "جلسات دفع ميسر",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "status", "created_at"],
                        name="moyasar_school_status_idx",
                    )
                ],
            },
        ),
    ]
