# Generated by Django 5.2.16 on 2026-08-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_refine_school_year_pricing"),
        ("subscriptions", "0017_alter_subscriptionscreenaddon_pricing_strategy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionscreenaddon",
            name="pricing_strategy",
            field=models.CharField(
                choices=[
                    ("auto_bundle", "تلقائي (شرائح)"),
                    ("manual_bundle", "يدوي (مبلغ إجمالي)"),
                    ("manual_per_screen", "يدوي (سعر لكل شاشة)"),
                ],
                default="auto_bundle",
                help_text="التلقائي: يعتمد السعر الشهري المعتمد لكل شاشة إضافية، ويُضرب في معامل الدورة (نصف سنوي/سنوي) حسب إعدادات المنصة.",
                max_length=30,
                verbose_name="طريقة التسعير",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("subscription_created", "إنشاء اشتراك"),
                            ("subscription_updated", "تعديل اشتراك"),
                            ("subscription_cancelled", "إلغاء اشتراك"),
                            ("subscription_expired", "انتهاء اشتراك"),
                            ("payment_recorded", "تسجيل دفعة"),
                            ("payment_reconciled", "تسوية دفعة"),
                            ("refund_recorded", "تسجيل استرداد"),
                            ("refund_completed", "تنفيذ استرداد"),
                            ("screens_added", "إضافة شاشات"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المنفّذ",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="الوصف"
                    ),
                ),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="تفاصيل"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, default="", max_length=45, verbose_name="عنوان IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المنفّذ",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_audit_logs",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="subscriptions.schoolsubscription",
                        verbose_name="الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق اشتراك",
                "verbose_name_plural": "سجلات تدقيق الاشتراكات",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "-created_at"],
                        name="audit_school_created_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="المبلغ المسترد (ر.س)",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("duplicate", "دفعة مكررة"),
                            ("service_issue", "مشكلة في الخدمة"),
                            ("cancelled_early", "إلغاء مبكر"),
                            ("billing_error", "خطأ في الفوترة"),
                            ("goodwill", "بادرة حسن نية"),
                            ("other", "سبب آخر"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="سبب الاسترداد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد التنفيذ"),
                            ("completed", "منفذ"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="مرجع الاسترداد لدى المزود",
                    ),
                ),
                (
                    "revokes_access",
                    models.BooleanField(
                        default=False,
                        help_text="عند التفعيل يتم إلغاء الاشتراك المرتبط بهذه العملية.",
                        verbose_name="إيقاف الاشتراك المرتبط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التنفيذ"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subscription_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سُجل بواسطة",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="subscriptions.subscriptionpaymentoperation",
                        verbose_name="عملية الدفع",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_refunds",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="subscriptions.schoolsubscription",
                        verbose_name="الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "استرداد اشتراك",
                "verbose_name_plural": "استردادات الاشتراكات",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "status"], name="refund_school_status_idx"
                    )
                ],
            },
        ),
    ]
