# Generated by Django 5.2.16 on 2026-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0018_alter_subscriptionscreenaddon_pricing_strategy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionemailnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("invoice", "فاتورة اشتراك"),
                    ("expiry", "تنبيه قرب انتهاء الاشتراك"),
                    ("verify_email", "توثيق البريد الإلكتروني"),
                ],
                max_length=20,
            ),
        ),
    ]
