# Generated by Django 5.2.16 on 2026-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0019_alter_subscriptionemailnotification_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="moyasarcheckout",
            name="extra_screens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="عدد الشاشات المشتراة فوق حد الباقة ضمن هذه العملية.",
                verbose_name="شاشات إضافية",
            ),
        ),
        migrations.AlterField(
            model_name="moyasarcheckout",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("renewal", "طلب تجديد"),
                    ("new", "طلب اشتراك جديد"),
                    ("screens", "شراء شاشات إضافية"),
                ],
                max_length=20,
            ),
        ),
    ]
