# Generated by Django 5.2.16 on 2026-08-17 23:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_screenoutage_cause"),
        ("subscriptions", "0022_moyasarcheckout_screen_addon_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moyasarcheckout",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ المخصوم من الإجمالي قبل إنشاء الدفعة.",
                max_digits=10,
                verbose_name="قيمة الخصم",
            ),
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="يُحفظ ويُقارن بأحرف كبيرة دون مسافات.",
                        max_length=40,
                        unique=True,
                        verbose_name="الكود",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "نسبة مئوية"), ("amount", "مبلغ ثابت")],
                        max_length=10,
                        verbose_name="نوع الخصم",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="بين 0.01 و 100 عند اختيار نوع النسبة.",
                        max_digits=5,
                        null=True,
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="مبلغ ثابت يُخصم من الإجمالي عند اختيار نوع المبلغ.",
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ الخصم (ر.س)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="بداية السماح"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="اتركه فارغاً لعدم تحديد نهاية زمنية.",
                        null=True,
                        verbose_name="نهاية السماح",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        help_text="إجمالي مرات الاستخدام المسموحة؛ عند بلوغه يتوقف الكود تلقائياً.",
                        verbose_name="عدد الأكواد المصدرة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="ملاحظات"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_codes_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "كود خصم",
                "verbose_name_plural": "أكواد الخصم",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="moyasarcheckout",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkouts",
                to="subscriptions.discountcode",
                verbose_name="كود الخصم",
            ),
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_discounted",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قيمة الخصم"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount_redemption",
                        to="subscriptions.moyasarcheckout",
                        verbose_name="جلسة الدفع",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="subscriptions.discountcode",
                        verbose_name="كود الخصم",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount_redemptions",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "استخدام كود خصم",
                "verbose_name_plural": "استخدامات أكواد الخصم",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="discountcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "amount"),
                    models.Q(("percent__gt", 0), ("percent__lte", 100)),
                    _connector="OR",
                ),
                name="discount_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "percent"), ("amount__gt", 0), _connector="OR"
                ),
                name="discount_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountredemption",
            constraint=models.UniqueConstraint(
                fields=("discount_code", "school"), name="uq_discount_once_per_school"
            ),
        ),
    ]
