# Generated by Django 5.2.16 on 2026-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_screenoutage_cause"),
        ("subscriptions", "0023_moyasarcheckout_discount_amount_discountcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="اتركها فارغة ليصلح الكود لكل الباقات.",
                related_name="discount_codes",
                to="core.subscriptionplan",
                verbose_name="الباقات المشمولة",
            ),
        ),
    ]
