# Generated by Django 5.2.17 on 2026-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0025_restore_tamara_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsubscription",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("budget", "الميزانية"),
                    ("not_used", "ضعف الاستخدام"),
                    ("technical", "مشكلة تقنية"),
                    ("competitor", "الانتقال إلى منافس"),
                    ("school_closed", "إغلاق أو دمج المدرسة"),
                    ("no_response", "تعذر التواصل"),
                    ("upgraded", "الترقية إلى باقة مدفوعة"),
                    ("other", "سبب آخر"),
                ],
                max_length=30,
                verbose_name="سبب الإلغاء أو عدم التجديد",
            ),
        ),
    ]
