# Generated by Django 5.2 for the platform mail center.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("local_reference", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("provider_id", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("internet_message_id", models.CharField(blank=True, default="", max_length=500)),
                ("direction", models.CharField(choices=[("inbound", "وارد"), ("outbound", "صادر")], db_index=True, max_length=12)),
                ("status", models.CharField(choices=[("queued", "بانتظار الإرسال"), ("sent", "تم الإرسال"), ("delivered", "تم التسليم"), ("delivery_delayed", "تأخر التسليم"), ("bounced", "مرتد"), ("failed", "فشل"), ("complained", "شكوى بريد مزعج"), ("suppressed", "محجوب"), ("received", "مستلم")], db_index=True, max_length=24)),
                ("from_address", models.CharField(blank=True, default="", max_length=500)),
                ("to_addresses", models.JSONField(blank=True, default=list)),
                ("cc_addresses", models.JSONField(blank=True, default=list)),
                ("bcc_addresses", models.JSONField(blank=True, default=list)),
                ("reply_to_addresses", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, db_index=True, default="", max_length=998)),
                ("text_body", models.TextField(blank=True, default="")),
                ("html_body", models.TextField(blank=True, default="")),
                ("preview", models.TextField(blank=True, default="")),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("provider_created_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("content_fetch_error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mailcenter_read_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "رسالة بريد", "verbose_name_plural": "رسائل البريد", "ordering": ("-provider_created_at", "-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="MailWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=160, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("occurred_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="mailcenter.mailmessage")),
            ],
            options={"verbose_name": "حدث بريد", "verbose_name_plural": "أحداث البريد", "ordering": ("-occurred_at", "-received_at", "-id")},
        ),
        migrations.AddIndex(model_name="mailmessage", index=models.Index(fields=["direction", "-provider_created_at"], name="mail_direction_created_idx")),
        migrations.AddIndex(model_name="mailmessage", index=models.Index(fields=["direction", "is_read", "-created_at"], name="mail_inbox_unread_idx")),
    ]
